module.exports = (sequelize, DataTypes) => {
    const Doctors = sequelize.define("Doctors", {
        firstName:{ 
            type:DataTypes.STRING 
        },
        lastName:{ 
            type:DataTypes.STRING 
        },
        email:{ 
            type:DataTypes.STRING 
        },
        password:{ 
            type:DataTypes.STRING 
        },
        phone:{ 
            type:DataTypes.STRING 
        },
        image:{ 
            type:DataTypes.STRING 
        },
        approved:{ 
            type:DataTypes.STRING 
        },
        verified:{ 
            type:DataTypes.STRING 
        },
        gmailId:{ 
            type:DataTypes.STRING,
        },
        gmail:{ 
            type:DataTypes.STRING,
            defaultValue:"0"
        },
        appleId:{ 
            type:DataTypes.STRING,
        },
        apple:{ 
            type:DataTypes.STRING,
            defaultValue:"0"
        },
    })
    return Doctors
}